### ISSUE TITLE
Why are editors not allowed to create the login link

### ISSUE THREAD

**Issue by mhuber84** [georgringer/login_link#7]
Hi Georg,
in https://github.com/georgringer/login_link/blob/e2913e5c860289d48dc543e0a2b6a700b8baed06/Classes/Service/Validation.php#L35 you allow only admin users. Can you explain why you did this? Is it just because it's not configurable yet or are there any security concerns?
Greetings, Marco

**Comment by georgringer** [comment]
security concerns

**Comment by nabossha** [comment]
@mhuber84 in case you are looking for a solution, I've patched Validation.php like this to adapt the (no longer available) TSconfig-option from femanager with login-link:

````
    public function isValid(string $table, int $recordId): bool
    {
        if (!in_array($table, ['be_users', 'fe_users'], true)) {
            return false;
        }
        $envKey = 'LOGINLINK_DISABLE_' . strtoupper(substr($table, 0, 2));
        if ($_ENV[$envKey] ?? false) {
            return false;
        }
        $user = $this->getBackendUser();
        // get the legacy TSconfig value from femanager and use it to decide upon the access-rights:
        $enableLoginAs = $user->isAdmin()
            ? true
            : (bool)($user->getUserTsConfig()->getUserTsConfigArray()['tx_femanager.']['UserBackend.']['enableLoginAs'] ?? false);

        $row = BackendUtility::getRecord($table, $recordId);

        // BE
        if ($table === 'be_users') {
            if ($row['disable'] || $row['admin']) {
                return false;
            }
            return $enableLoginAs;
        }

        // FE
        // todo allow editors to login for fe_users
        return $enableLoginAs;
    }
````

**Comment by mhuber84** [comment]
@nabossha thank you, I did something similar. :-)

With this patch I can configure a user group uid which is allowed to use the login link:

`return $user->isAdmin() || $user->isMemberOfGroup((int)$user->getUserTsConfig()->getUserTsConfigArray()['tx_loginlink.']['group']);`

Perhaps it would be better, to configure the group uid not in the user TsConfig but in the page TsConfig. Then it would be possible to configure different groups per page tree. But that are details ;-)
